/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package top.lizhistudio.app.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2021-03-09")
public enum MESSAGE_TYPE implements org.apache.thrift.TEnum {
  LOG(1),
  ERROR(2),
  STOP(3);

  private final int value;

  private MESSAGE_TYPE(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static MESSAGE_TYPE findByValue(int value) { 
    switch (value) {
      case 1:
        return LOG;
      case 2:
        return ERROR;
      case 3:
        return STOP;
      default:
        return null;
    }
  }
}
