---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  动画类型
---
---@link  https://www.immomo.comAnimType.html
---@class AnimType @parent class
---@public field name string 
---@type AnimType
AnimType = {
	---
	---  动画类型
	---
	BottomToTop = "value",

	---
	---  动画类型
	---
	RightToLeft = "value",

	---
	---  动画类型
	---
	Scale = "value",

	---
	---  动画类型
	---
	Default = "value",

	---
	---  动画类型
	---
	LeftToRight = "value",

	---
	---  动画类型
	---
	None = "value",

	---
	---  动画类型
	---
	TopToBottom = "value",

	---
	---  动画类型
	---
	Fade = "value"

}