---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  应用工具类
---
---@class Application @parent class
---@public field name string 
---@type Application
Application= {
	_priveta_class_name = "Application"}

---
---  前台切换后台回调
---
---@param frontToBackCallback fun():void
---	 function...end 
---		 前台切换后台回调
---@return Application 
function Application:setForeground2BackgroundCallback(frontToBackCallback)
	return self
end

---
---  后台切换前台回调
---
---@param backToFrontCallback fun():void
---	 function...end 
---		 后台切换前台回调
---@return Application 
function Application:setBackground2ForegroundCallback(backToFrontCallback)
	return self
end

