---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  画布动画
---
---
---  画布动画描述类，包含所有画布动画对象方法
---
---@class CanvasAnimation @parent class
---@public field name string 
---@type CanvasAnimation
local _class = {
	_priveta_class_name = "CanvasAnimation"}

---
---  设置横向锚点值
---
---@param pivotX number  锚点值,范围0~1
---@return CanvasAnimation 
function _class:setPivotX(pivotX)
	return self
end

return _class