---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  指定每个视图之间的间隔以及大小
---
---@class CollectionViewLayout @parent class
---@public field name string 
---@type CollectionViewLayout
local _class = {
	_priveta_class_name = "CollectionViewLayout"}

---
---  构造方法
---
---@return CollectionViewLayout 
function CollectionViewLayout()
	return _class
end

---
---  设置网格布局的内边距
---
---@param top number  top：上边距
---@param left number  left：左边距
---@param bottom number  bottom：下边距
---@param right number  right：右边距
---@return CollectionViewLayout 
function _class:layoutInset(top, left, bottom, right)
	return self
end

---
---  设置cell之间的纵向间隔
---
---@param lineSpace number  cell之间的纵向间隔
---@return CollectionViewLayout 
---@note  无论滚动方向是横向还是纵向，lineSpacing都代表cell之间的纵向间隔
function _class:lineSpacing(lineSpace)
	return self
end

---
---  获取cell之间的纵向间隔
---
---@return number 
---@note  无论滚动方向是横向还是纵向，lineSpacing都代表cell之间的纵向间隔
function _class:lineSpacing()
	return 0
end

---
---  设置cell之间的横向间隔
---
---@param itemSpace number  cell之间的横向间隔
---@return CollectionViewLayout 
---@note  无论滚动方向是横向还是纵向，lineSpacing都代表cell之间的横向间隔
function _class:itemSpacing(itemSpace)
	return self
end

---
---  获取cell之间的横向间隔
---
---@return number 
---@note  无论滚动方向是横向还是纵向，lineSpacing都代表cell之间的横向间隔
function _class:itemSpacing()
	return 0
end

---
---  设置列数(竖向滚动)、行数(横向滚动)
---
---@param spanCount number  列数(竖向滚动)、行数(横向滚动)
---@return CollectionViewLayout 
function _class:spanCount(spanCount)
	return self
end

---
---  获取列数(竖向滚动)、行数(横向滚动)
---
---@return number 
function _class:spanCount()
	return 0
end

return _class