---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  内容显示模式
---
---@link  https://www.immomo.comContentMode.html
---@class ContentMode @parent class
---@public field name string 
---@type ContentMode
ContentMode = {
	---
	---  内容显示模式
	---
	SCALE_TO_FILL = "value",

	---
	---  内容显示模式
	---
	SCALE_ASPECT_FIT = "value",

	---
	---  内容显示模式
	---
	SCALE_ASPECT_FILL = "value",

	---
	---  内容显示模式
	---
	CENTER = "value"

}