---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  全局圆角切割相关控制
---
---@class CornerManager @parent class
---@public field name string 
---@type CornerManager
CornerManager= {
	_priveta_class_name = "CornerManager"}

---
---  开启默认切割
---
---@param open boolean  开启后，设置圆角不需要再调用clipToBounds，关闭后，需要用户自行控制是否clipToBounds
---@return CornerManager 
function CornerManager:openDefaultClip(open)
	return self
end

