---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  网络模块加密类型，提供加密和不加密2种方式, 默认为加密方式
---
---@link  https://www.immomo.comEncType.html
---@class EncType @parent class
---@public field name string 
---@type EncType
EncType = {
	---
	---  网络模块加密类型，提供加密和不加密2种方式, 默认为加密方式
	---
	NO = "value",

	---
	---  网络模块加密类型，提供加密和不加密2种方式, 默认为加密方式
	---
	NORMAL = "value"

}