---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  网络返回结果错误信息的键值，可以通过ErrorKey各枚举信息来获取详细错误信息
---
---@link  https://www.immomo.comErrorKey.html
---@class ErrorKey @parent class
---@public field name string 
---@type ErrorKey
ErrorKey = {
	---
	---  网络返回结果错误信息的键值，可以通过ErrorKey各枚举信息来获取详细错误信息
	---
	MSG = "value",

	---
	---  网络返回结果错误信息的键值，可以通过ErrorKey各枚举信息来获取详细错误信息
	---
	CODE = "value"

}