---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  <#summary#>
---
---@link  https://www.immomo.comFontStyle.html
---@class FontStyle @parent class
---@public field name string 
---@type FontStyle
FontStyle = {
	---
	---  <#summary#>
	---
	NORMAL = "value",

	---
	---  <#summary#>
	---
	ITALIC = "value",

	---
	---  <#summary#>
	---
	BOLD = "value",

	---
	---  <#summary#>
	---
	BOLD_ITALIC = "value"

}