---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  渐变色方向
---
---@link  https://www.immomo.comGradientType.html
---@class GradientType @parent class
---@public field name string 
---@type GradientType
GradientType = {
	---
	---  渐变色方向
	---
	RIGHT_TO_LEFT = "value",

	---
	---  渐变色方向
	---
	BOTTOM_TO_TOP = "value",

	---
	---  渐变色方向
	---
	LEFT_TO_RIGHT = "value",

	---
	---  渐变色方向
	---
	TOP_TO_BOTTOM = "value"

}