---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  线性布局容器的布局方向枚举值
---
---@link  https://www.immomo.comLinearType.html
---@class LinearType @parent class
---@public field name string 
---@type LinearType
LinearType = {
	---
	---  线性布局容器的布局方向枚举值
	---
	VERTICAL = "value",

	---
	---  线性布局容器的布局方向枚举值
	---
	HORIZONTAL = "value"

}