---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  通知环境枚举
---
---
---  在主工程桥接的GlobalEvent环境全局参数，主要用来指定dst_l_evn标识目标环境值，多环境可用 + 连接
---
---@link  https://www.immomo.comLocales.html
---@class Locales @parent class
---@public field name string 
---@type Locales
Locales = {
	---
	---  通知环境枚举
	---
	---
	---  在主工程桥接的GlobalEvent环境全局参数，主要用来指定dst_l_evn标识目标环境值，多环境可用 + 连接
	---
	NATIVE = "value",

	---
	---  通知环境枚举
	---
	---
	---  在主工程桥接的GlobalEvent环境全局参数，主要用来指定dst_l_evn标识目标环境值，多环境可用 + 连接
	---
	WEEX = "value",

	---
	---  通知环境枚举
	---
	---
	---  在主工程桥接的GlobalEvent环境全局参数，主要用来指定dst_l_evn标识目标环境值，多环境可用 + 连接
	---
	MK = "value",

	---
	---  通知环境枚举
	---
	---
	---  在主工程桥接的GlobalEvent环境全局参数，主要用来指定dst_l_evn标识目标环境值，多环境可用 + 连接
	---
	LUA = "value"

}