---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  视图宽高的测量模式
---
---@link  https://www.immomo.comMeasurementType.html
---@class MeasurementType @parent class
---@public field name string 
---@type MeasurementType
MeasurementType = {
	---
	---  视图宽高的测量模式
	---
	WRAP_CONTENT = "value",

	---
	---  视图宽高的测量模式
	---
	MATCH_PARENT = "value"

}