---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  动画重复类型
---
---@link  https://www.immomo.comRepeatType.html
---@class RepeatType @parent class
---@public field name string 
---@type RepeatType
RepeatType = {
	---
	---  动画重复类型
	---
	REVERSE = "value",

	---
	---  动画重复类型
	---
	FROM_START = "value",

	---
	---  动画重复类型
	---
	NONE = "value"

}