---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  键盘返回键样式
---
---
---  主要用于输入框进入编辑模式后，键盘的返回键位置，显示的文本样式
---
---@note  主要用于输入框等组件，详情见[EditTextView](EditTextView)
---@link  https://www.immomo.comReturnType.html
---@class ReturnType @parent class
---@public field name string 
---@type ReturnType
ReturnType = {
	---
	---  键盘返回键样式
	---
	---
	---  主要用于输入框进入编辑模式后，键盘的返回键位置，显示的文本样式
	---
	---@note  主要用于输入框等组件，详情见[EditTextView](EditTextView)
	Send = "value",

	---
	---  键盘返回键样式
	---
	---
	---  主要用于输入框进入编辑模式后，键盘的返回键位置，显示的文本样式
	---
	---@note  主要用于输入框等组件，详情见[EditTextView](EditTextView)
	Next = "value",

	---
	---  键盘返回键样式
	---
	---
	---  主要用于输入框进入编辑模式后，键盘的返回键位置，显示的文本样式
	---
	---@note  主要用于输入框等组件，详情见[EditTextView](EditTextView)
	Done = "value",

	---
	---  键盘返回键样式
	---
	---
	---  主要用于输入框进入编辑模式后，键盘的返回键位置，显示的文本样式
	---
	---@note  主要用于输入框等组件，详情见[EditTextView](EditTextView)
	Default = "value",

	---
	---  键盘返回键样式
	---
	---
	---  主要用于输入框进入编辑模式后，键盘的返回键位置，显示的文本样式
	---
	---@note  主要用于输入框等组件，详情见[EditTextView](EditTextView)
	Go = "value",

	---
	---  键盘返回键样式
	---
	---
	---  主要用于输入框进入编辑模式后，键盘的返回键位置，显示的文本样式
	---
	---@note  主要用于输入框等组件，详情见[EditTextView](EditTextView)
	Search = "value",

	---
	---  键盘返回键样式
	---
	---
	---  主要用于输入框进入编辑模式后，键盘的返回键位置，显示的文本样式
	---
	---@note  主要用于输入框等组件，详情见[EditTextView](EditTextView)
	Continue = "value"

}