---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  获取或设置客户端的一些状态
---
---@note  这是静态类，不需要实例化
---@class System @parent class
---@public field name string 
---@type System
System= {
	_priveta_class_name = "System"}

---
---  获取系统版本
---
---@return string 返回描述系统版本的字符串
function System:OSVersion()
	return "string"
end

---
---  获取App版本字符串
---
---@return string 返回描述App版本的字符串
function System:AppVersion()
	return "string"
end

---
---  获取SDK版本，和SDKVersionInt对应
---
---@return string 返回描述SDK系统版本的字符串
function System:SDKVersion()
	return "string"
end

---
---  获取sdk版本，和SDKVersion对应
---
---@return number 返回描述系统版本的整数值
function System:SDKVersionInt()
	return 0
end

---
---  获取系统版本，和OSVersion对应，iOS返回大版本数字
---
---@return number 返回描述系统版本的整数值, 如4.0，则此处返回4
function System:OSVersionInt()
	return 0
end

---
---  是否为ios
---
---@return boolean 
function System:iOS()
	return true
end

---
---  是否为Android
---
---@return boolean 
function System:Android()
	return true
end

---
---  在主线程下次渲染前执行操作
---
---@param callback fun():void
---	 需要执行的内容，格式为：
---		 ```
---		 function()
---			--- 操作内容 
---		end
---		``` 
---@return System 
function System:asyncDoInMain(callback)
	return self
end

---
---  获取当前设备的像素缩放比
---
---@return number 返回当前设备的像素缩放比
function System:scale()
	return 0
end

---
---  获取屏幕大小
---
---@return Size 返回屏幕尺寸
function System:screenSize()
	return Size()
end

---
---  获取导航栏高度
---
---@return number 返回导航栏高度
---@note  废弃，使用[window](window)中相关接口
function System:navBarHeight()
	return 0
end

---
---  获取状态栏高度
---
---@return number 返回状态栏高度
---@note  废弃，使用[window](window)中相关接口
function System:stateBarHeight()
	return 0
end

---
---  获取homeIndicator高度
---
---@return number 返回homeIndicator高度
---@note  废弃，使用[window](window)中相关接口
function System:homeIndicatorHeight()
	return 0
end

---
---  获取设备信息, 如iPhone10,3
---
---@return string 返回设备型号，如iPhone10,3
function System:deviceInfo()
	return "string"
end

---
---  获取tabBar高度
---
---@return number 返回tabBar高度
---@note  废弃，使用[window](window)中相关接口
function System:tabBarHeight()
	return 0
end

---
---  延迟执行任务
---
---@param callback fun():void
---	 需要被延迟执行的任务，以callback形式传入。样式为：
---		```
---		function()
---			--- do semoting ...
---		end
---		```
---		
---@param delay number  延迟时间，单位：s
---@return System 
---@note  虚拟机和window销毁，就会释放
function System:setTimeOut(callback, delay)
	return self
end

---
---  Android切换全屏或非全屏
---
---@param fullscreen boolean  a: true 表示切换至全屏 false：表示切换至非全屏
---@return System 
---@note  废弃，使用[window](window)中相关接口
function System:switchFullscreen(fullscreen)
	return self
end

---
---  展示状态栏
---
---@return System 
function System:showStatusBar()
	return self
end

---
---  移除状态栏
---
---@return System 
function System:hideStatusBar()
	return self
end

---
---  设置屏幕亮度，brightness:亮度, 在 1 至 255 之间
---
---@param brightness number  brightness:亮度, 在 1 至 255 之间
---@return System 
function System:changeBright(brightness)
	return self
end

---
---  获取当前窗口屏幕亮度值，介于 1 至 255 之间
---
---@return number 返回当前窗口屏幕亮度值，介于 1 至 255 之间
function System:getBright()
	return 0
end

