---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  TabSegmentView的标签布局样式
---
---@note  默认居左，可以设置为居中，居右不常用
---@link  https://www.immomo.comTabSegmentAlignment.html
---@class TabSegmentAlignment @parent class
---@public field name string 
---@type TabSegmentAlignment
TabSegmentAlignment = {
	---
	---  TabSegmentView的标签布局样式
	---
	---@note  默认居左，可以设置为居中，居右不常用
	CENTER = "value",

	---
	---  TabSegmentView的标签布局样式
	---
	---@note  默认居左，可以设置为居中，居右不常用
	RIGHT = "value",

	---
	---  TabSegmentView的标签布局样式
	---
	---@note  默认居左，可以设置为居中，居右不常用
	LEFT = "value"

}