---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  提供三种设置文本的展示样式
---
---
---  一般应用到Label和EditTextView上,设置文本的展示样式，默认居左展示
---
---@link  https://www.immomo.comTextAlign.html
---@class TextAlign @parent class
---@public field name string 
---@type TextAlign
TextAlign = {
	---
	---  提供三种设置文本的展示样式
	---
	---
	---  一般应用到Label和EditTextView上,设置文本的展示样式，默认居左展示
	---
	CENTER = "value",

	---
	---  提供三种设置文本的展示样式
	---
	---
	---  一般应用到Label和EditTextView上,设置文本的展示样式，默认居左展示
	---
	RIGHT = "value",

	---
	---  提供三种设置文本的展示样式
	---
	---
	---  一般应用到Label和EditTextView上,设置文本的展示样式，默认居左展示
	---
	LEFT = "value"

}