---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  lua userdata类型判断工具
---
---
---  当业务使用过程中遇到需求，需要判断某个userdata是数组还是字典，使用该方法
---
---@class TypeUtils @parent class
---@public field name string 
---@type TypeUtils
TypeUtils= {
	_priveta_class_name = "TypeUtils"}

---
---  是否是字典
---
---@param obj userdata  待判断的数据
---@return boolean 是否是字典类型
---@note  在iOS网络回调中，如果遇到json为[]空时，会被转换为字典，需要注意
function TypeUtils:isMap(obj)
	return true
end

---
---  是否是数组
---
---@param obj userdata  待判断的数据
---@return boolean boolean
---@note  在iOS网络回调中，如果遇到json为[]空时，会被转换为字典，需要注意
function TypeUtils:isArray(obj)
	return true
end

