---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  属性动画传值类型
---
---
---  当执行FrameAnimation时，不想传入当前视图的值时，可以传入该全局变量标记，使用视图当前的属性值作为目标值
---
---@link  https://www.immomo.comValueType.html
---@class ValueType @parent class
---@public field name string 
---@type ValueType
ValueType = {
	---
	---  属性动画传值类型
	---
	---
	---  当执行FrameAnimation时，不想传入当前视图的值时，可以传入该全局变量标记，使用视图当前的属性值作为目标值
	---
	CURRENT = "value",

	---
	---  属性动画传值类型
	---
	---
	---  当执行FrameAnimation时，不想传入当前视图的值时，可以传入该全局变量标记，使用视图当前的属性值作为目标值
	---
	NONE = "value"

}